---
- name: Create Influxdb storage
  docker_volume:
    name: influxdb-storage

- name: Influxdb container
  docker_container:
    name: influxdb
    image: influxdb
    state: started
    ports:
    - "8086:8086"
    volumes:
    - influxdb-storage:/var/lib/influxdb

- name: Install python Influxdb
  command: pip install influxdb

- name: Install python datetime
  command: pip install datetime

- name: Install python rfc3339
  command: pip install rfc3339

- name: Install python pprint
  command: pip install pprint

- name: copy influx-import script
  copy:
    src: netq-import.py
    dest: /home/cumulus/netq-import.py
    owner: cumulus
    group: cumulus

- name: Create NetQ influx DB
  influxdb_database:
    hostname: "localhost"
    database_name: "netq"
...
