---
- name: Collect System Parameters in JSON
  shell: /usr/cumulus/bin/decode-syseeprom -j
  register: decode_syseeprom_json
  changed_when: false

- name: Create config folder locally
  file:
    path: config/{{ fabric_name }}/{{ inventory_hostname }}
    state: directory
    recurse: yes
  delegate_to: localhost
  become: false
  tags:
    - local

- name: Convert JSON into Ansible native variable type
  set_fact:
    decode_syseeprom: "{{decode_syseeprom_json.stdout | from_json }}"
  changed_when: false
