---
- hosts: oob-mgmt-server 
  become: true
  roles:
  - { role: oob-mgmt-server, tags: ['deploy'] }
  - { role: app-grafana, tags: ['deploy','grafana'] }
  - { role: app-netbox, tags: ['deploy','netbox'] }
  - { role: app-ngrok, tags: ['deploy','ngrok'] }
  - { role: app-influxdb, tags: ['deploy','influxdb'] }

- hosts: netq-ts
  become: true
  roles:
  - { role: setup-netq-ts, tags: ['deploy'] }

- hosts: pod1spine 
  become: true
  roles:
  - { role: setup-switch, tags: ['deploy'] }
  - { role: interfaces, tags: ['deploy','update'] }
  - { role: frr, tags: ['deploy','update'] }

- hosts: pod1leaf
  become: true 
  roles:
  - { role: setup-switch, tags: ['deploy'] }
  - { role: interfaces, tags: ['deploy','update'] }
  - { role: frr, tags: ['deploy','update'] }

- hosts: pod1service
  become: true 
  roles:
  - { role: setup-switch, tags: ['deploy'] }
  - { role: interfaces, tags: ['deploy','update'] }
  - { role: frr, tags: ['deploy','update'] }

- hosts: 3tierspine
  become: true 
  roles:
  - { role: setup-switch, tags: ['deploy'] }
  - { role: interfaces, tags: ['deploy','update'] }
  - { role: frr, tags: ['deploy','update'] }

- hosts: edgeexit
  become: true 
  roles:
  - { role: setup-switch, tags: ['deploy'] }
  - { role: interfaces, tags: ['deploy','update'] }
  - { role: frr, tags: ['deploy','update'] }

- hosts: edgerouter
  become: true 
  roles:
  - { role: setup-switch, tags: ['deploy'] }
  - { role: interfaces, tags: ['deploy','update'] }
  - { role: frr, tags: ['deploy','update'] }

- hosts: server01,server02,server05,server06,server09,server10
  become: true 
  roles:
  - { role: setup-server, tags: ['deploy'] }
  - { role: server-multitenant, tags: ['deploy'] }
  - { role: app-netq, tags: ['deploy', 'netq'] }
  - { role: server-keepalive, tags: ['keepalive', 'update'] }

- hosts: server07,server08
  become: true 
  roles:
  - { role: setup-server, tags: ['deploy'] }
  - { role: server-multitenant, tags: ['deploy'] }
  - { role: app-netq, tags: ['deploy', 'netq'] }
...
