switch_role: leaf
peerlinks:
  - swp49
  - swp50
fabric_links:
  - swp51
  - swp52
  - swp53
  - swp54
devices:
  leaf01:
    rack: 01
    routing:
      bgp:
        asn: 65101
    interfaces:
      loopback: 
        ipv4: "10.10.10.1/32"
      svis:
        1000:
          vrf: tenant1
          ipv4: 192.168.10.2/24
          ipv4_vrr: 192.168.10.1/24
          ipv6_prefix: fc00:10::/64
          ipv6: fc00:10::2/64
          ipv6_vrr: fc00:10::1/64
  leaf02:
    rack: 01
    routing:
      bgp:
        asn: 65102
    interfaces:
      loopback: 
        ipv4: 10.10.10.2/32
      svis:
        1000:
          vrf: tenant1
          ipv4: 192.168.10.3/24
          ipv4_vrr: 192.168.10.1/24
          ipv6_prefix: fc00:10::/64
          ipv6: fc00:10::3/64
          ipv6_vrr: fc00:10::1/64
  leaf03:
    rack: 02
    routing:
      bgp:
        asn: 65103
    interfaces:
      loopback: 
        ipv4: 10.10.10.3/32
      svis:
        1000:
          vrf: tenant1
          ipv4: 192.168.10.2/24
          ipv4_vrr: 192.168.10.1/24
          ipv6_prefix: fc00:10::/64
          ipv6: fc00:10::2/64
          ipv6_vrr: fc00:10::1/64
  leaf04:
    rack: 02
    routing:
      bgp:
        asn: 65104
    interfaces:
      loopback:
        ipv4: 10.10.10.4/32
      svis:
        1000:
          vrf: tenant1
          ipv4: 192.168.10.3/24
          ipv4_vrr: 192.168.10.1/24
          ipv6_prefix: fc00:10::/64
          ipv6: fc00:10::3/64
          ipv6_vrr: fc00:10::1/64
