---
- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking

- name: Reboot system
  reboot:
    reboot_timeout: 1200
    test_command: mount      

- name: Disable chrony in default vrf 
  systemd:
    name: chrony
    state: stopped
    enabled: no

- name: Enable chrony in management vrf 
  systemd:
    name: chrony@mgmt
    state: started
    enabled: yes
...
