---
- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking

- name: Reboot system
  reboot:
    reboot_timeout: 1200
    test_command: mount      
...
