---
- hosts: oob 
  become: true
  roles:
  - oob-mgmt-server
  - app-grafana
  - app-netbox
  - app-ngrok

- hosts: netq-ts
  become: true
  roles:
  - setup-netq-ts
    tags: [ 'never', 'netq' ] 

- hosts: spines,superspine
  become: true
  roles:
  - setup-switch
  - switch-spine

- hosts: leafs,edge,router
  become: true 
  roles:
  - setup-switch
  - switch-leaf

- hosts: servers-rack1,servers-rack3 
  become: true 
  roles:
  - setup-server
  - server-multitenant
  - app-netq

- hosts: servers-rack2 
  become: true 
  roles:
  - setup-server
  - server-evpn
  - app-netq
...
