---
- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved.service
    state: stopped
    enabled: no

- name: Remove resolve.conf
  file:
   path: /etc/resolv.conf
   state: absent

- name: Create resolve.conf
  copy:
    content: ""
    dest: /etc/resolv.conf
    force: no
    group: sys
    owner: root
    mode: 0644

- name: Add dns server
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 8.8.8.8'

- name: Install additional packages
  apt:
    name: ['git','screen','python3-pip','unzip']
    update_cache: yes
    state: present
    force: yes

- name: Install Pyyaml
  command: pip3 install PyYAML

- name: Install Pynetbox
  command: pip3 install pynetbox==3.4.7

- name: Pip installs
  pip:
    name:
      - docker

- name: Add Cumulus Apt Key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable 
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes

- name: adding cumulus to group docker
  user:
    name: cumulus
    groups: docker
    append: yes

- name: Get docker compose 
  get_url: 
    url: https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose

- name: Chown docker-compose
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
...
